# Variables, data frames, indexing, functions etc

## Computer representation of numbers

Real numbers are not stored exactly on computers. Use binary version of ``scientific'' notation e.g. $1.234 \times 10^2$. This needs care e.g.

In [1]:

x = seq(0, 0.5, 0.1) ##generate a sequence from 0 to 0.5 in steps of 0.1
x ##Look at x


[1] 0.0 0.1 0.2 0.3 0.4 0.5

Is x equal to (0, 0.1, 0.2, 0.3, 0.4, 0.5)? To find out, type

In [2]:
x == c(0, 0.1, 0.2, 0.3, 0.4, 0.5)


[1]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE

This is known as _FAQ 7.31_: see [https://cran.r-project.org/doc/FAQ/R-FAQ.html].

## Rounding problems

Tiny inaccuracies can accumulate:
  
The sample variance of a vector ```x``` is often calculated as  
  
   $var (x) = (\sum x^2-n\bar{x}^2) / (n-1)$

Try it out and compare it with ```var()```: 

In [3]:
myvar = function(x) (sum(x^2) - length(x) * mean(x)^2) / (length(x) - 1) #define a function myvar(x) to estimate the variance
x = seq(1:100)
myvar(x)
var(x)
x = seq(1:100) + 10000000000
myvar(x)
var(x)

[1] 841.6667

[1] 841.6667

[1] 0

[1] 841.6667

Can you see why there was a problem?

## Variables

Basic Types of Variables

Variables are the equivalent of memories in your calculator. But you can have unlimited (almost!) quantities of them and they have names of your choosing. And different   types. The basic types are

 + integer
 + double
 + character
 + logical: these take one of the two values ```TRUE``` or ```FALSE```
    (or ```NA```, see later)
 + factor or categorical
 

## More Specialised Classes

As well as the basic types of variables, R recognises many more complicated  objects such as 

* **vectors**, **matrices**, **arrays**: groups of objects all of the same type
 
* **lists** of other objects which may be of different types

*  Specialised objects such as **Dates**, **Linear Model fits**

  
## Special values of objects

There are some types of data which need to be treated specially in calculations:

* ```NA``` The value ```NA``` is given to any data which R
    knows to be missing. This is not a character string, so a
    character string with value ```"NA"``` will be treated differently
    from one with the value ```NA```.

*  ```Inf``` The result of e.g. dividing any non-zero number by zero

*  ```NaN``` The result of e.g. attempting to find the logarithm of a
 negative number.

In [4]:
 
as.numeric(c("a", "1"))
x / 0
log(-x)

Warning message in eval(expr, envir, enclos):
"NAs introduced by coercion"

[1] NA  1

[1] Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf
 [19] Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf
 [37] Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf
 [55] Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf
 [73] Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf
 [91] Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf

Warning message in log(-x):
"NaNs produced"

[1] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
 [19] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
 [37] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
 [55] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
 [73] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
 [91] NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

   
## Factors

Factors are variables which can only take one of a finite set of discrete values. They naturally occur as vectors, and can be

* **numeric** e.g. drug doses with values 1mg, 2mg, 5mg
* or **character** e.g. voting intention with values Liberal Democrat, Conservative, Labour, Other
  
Although factors are stored as numbers, along with the label
corresponding to each number, they cannot be treated as numeric. Would
it make sense to ask R to calculate ```mean(voting intention)```?

A more useful function for factors is ```table``` which will count
how many of each value occur in the vector.


## Ordered Factors

Some factor variables have a natural ordering. Drug doses do, but
voting intentions usually do not. R will treat the two types
differently. It is important not to allow R to treat non-ordered
factors as ordered ones, since the results could be meaningless.

## Creating factors

Use ```cut``` to create factor variables from continuous ones:

In [5]:
age <- runif(100) * 50
table(cut(age, c(0, 10, 20, 30, 40, 50)))


 (0,10] (10,20] (20,30] (30,40] (40,50] 
     13      20      27      20      20 

The function `factor()` can be used to create factor variables from characters.

## Data frames 
* For storing data which is a collection of observations (rows) of a set of variables (columns). E.g. book titles and prices.
* Similar to a matrix but variables in different columns can have different types.
* Always the same number of entries in each row, although some may be missing (```NA```).
* Can be formed by reading in data e.g. from a spreadsheet, or constructed using the function ```data.frame```.

You will need the following file [Example Chicken weights csv](../data/chickwt.csv)

Download the file from the link to the folder where you are running R.

In [6]:
mydata = read.csv('chickwt.csv')
head(x = mydata)

weight feed     
1 179    horsebean
2 160    horsebean
3 136    horsebean
4 227    horsebean
5 217    horsebean
6 168    horsebean

## Lists

A data frame is a kind of list, which is a vector
of objects of possibly different types. For example, an employee
record might be created by

In [7]:
Empl = list(employee = "Anna", spouse = "Fred", children = 3,
             child.ages = c(4, 7, 9))
Empl

$employee
[1] "Anna"

$spouse
[1] "Fred"

$children
[1] 3

$child.ages
[1] 4 7 9

Try the following:

In [8]:
Empl[[1]]
Empl$spouse

Empl[[4]]
length(Empl[[4]]) # numeric vector of length 3

Empl[4]
length(Empl[4]) # list of length 1
Empl[2:4]  # this works


[1] "Anna"

[1] "Fred"

[1] 4 7 9

[1] 3

$child.ages
[1] 4 7 9

[1] 1

$spouse
[1] "Fred"

$children
[1] 3

$child.ages
[1] 4 7 9

Components are always numbered and may be referred to by
number. e.g. ```Empl[[1]]```. If they are named, can also be
referred to by name using the \$ operator eg. ```Empl$spouse```

## Keeping track of objects

Once you have created some objects, how do you remind yourself what you called them? 

In [9]:
ls()
str(Empl)

[1] "age"    "Empl"   "mydata" "myvar"  "x"

List of 4
 $ employee  : chr "Anna"
 $ spouse    : chr "Fred"
 $ children  : num 3
 $ child.ages: num [1:3] 4 7 9


```ls()``` lists the names of all the objects in you workspace and ```str()`` gives information about a specific object.

## Operators

Arithmetic Operators: ```+, - , /, *, ^```.

In [10]:
3^2
10 %% 3 # modulo reduction
10 %/% 3 # integer division

a = matrix(1:4, nrow=2)
b = matrix(c(2, 1, 2, 4), nrow=2)
a %*% b # matrix multiplication

[1] 9

[1] 1

[1] 3

[,1] [,2]
[1,] 5    14  
[2,] 8    20

Operators can also be used on vectors, with recycling if necessary. 

In [11]:
x = c(1, 2, 3, 4)
y = c(5, 6)
x + 3
#(4,5,6,7) and
x + y
#(6,8,8,10)

[1] 4 5 6 7

[1]  6  8  8 10

## Logical operators

* ```==``` (equal), ```!=``` (not equal), ```>, <, >=, <=```

* ```!``` (not), ```|``` (or), ```||``` (or), ```&``` (and) ```&&``` (and)

* ```|```, ```&``` work on vectors 

* ```||``` and ```&&``` consider only one element

Examples:

In [12]:
x = c(TRUE, FALSE, TRUE)
y = c(FALSE, TRUE, TRUE)

x | y
x || y

x & y
x && y
x[3] && y[3]

[1] TRUE TRUE TRUE

[1] TRUE

[1] FALSE FALSE  TRUE

[1] FALSE

[1] TRUE

The && is also a "short circuit and", i.e. it won't evaluate its second argument if the first argument is FALSE. Compare the following

## Dates
Example:

In [13]:
myDate = as.Date('10-Jan-1993', format="%d-%b-%Y")

class(myDate)
as.numeric(myDate)

myDate2 = as.Date('10-Jan-1994', format="%d-%b-%Y")

myDate2-myDate # can substract two dates

[1] "Date"

[1] 8410

Time difference of 365 days

## Some useful functions
Look at the following functions (you can use R help to see what they do using "?funcname"):

In [14]:
c(1, "a")
1:5
c(1,2,3,4,5)
seq(1, 10, by=2) #sequence from 1 to 10 in steps of 2
rep(c(1, 2), times=3)  # replicate (1,2) 3 times
rep(c(1, 2), each=3)   # replicate (1,2) first entry 3 times and second 3 times 
rep(c(1, 2), c(2, 3))  # replicate (1,2) first entry 2 times and second 3 times


paste(c(1, 2), c('x', 'y', 'z')) # create vector of concatenations of the two vectors
paste(c(1, 2), c('x', 'y', 'z'), collapse=' ') # create the previous vector and concatenate its entries into a single string

sort(mydata$weight) # sort ascending
sort(mydata$weight, decreasing=TRUE) # sort descending

table(rpois(20, 5)) # create a table with 20 random poisson variables with rate parameter lambda=5

[1] "1" "a"

[1] 1 2 3 4 5

[1] 1 2 3 4 5

[1] 1 3 5 7 9

[1] 1 2 1 2 1 2

[1] 1 1 1 2 2 2

[1] 1 1 2 2 2

[1] "1 x" "2 y" "1 z"

[1] "1 x 2 y 1 z"

[1] 108 124 136 140 141 143 148 153 158 160 168 169 171 179 181 193 199 203 206
[20] 213 216 217 222 226 227 229 230 242 243 244 248 248 250 257 257 258 260 260
[39] 263 267 271 271 283 295 297 303 309 315 316 318 318 320 322 325 327 329 332
[58] 334 339 340 341 344 352 359 368 379 380 390 392 404 423

[1] 423 404 392 390 380 379 368 359 352 344 341 340 339 334 332 329 327 325 322
[20] 320 318 318 316 315 309 303 297 295 283 271 271 267 263 260 260 258 257 257
[39] 250 248 248 244 243 242 230 229 227 226 222 217 216 213 206 203 199 193 181
[58] 179 171 169 168 160 158 153 148 143 141 140 136 124 108


 0  2  3  4  5  6  7  9 10 
 1  4  3  3  3  1  3  1  1 

## Matrices, arrays and indexing

In [15]:
(mymat = matrix(1:12, 3, 4)) # Entries go down columns unless you specify byrow=TRUE.
dim(mymat)
myarr = mymat
dim(myarr) = c(3,2,2) # creating an array
myarr
myarr[,,1] # using indexing to select the entries of the arrays third dimension y

x = c(2,4,6,8,10,12)
names(x) = c("a", "b", "c", "d", "e", "f")

## Use different types of indices
x[c(1,3,6,5)] 
x[c("a","c","f", "e")] ## gives same as above
x[c(TRUE,FALSE,TRUE,rep(FALSE,3))] # can also use logical vectors to select entries
x[c(-1,-4)] ## exclude first and fourth entry

y = x
(y[]  =  0 ) ## Empty. Select all, useful to replace all vector entries
names(y) ## will be the same as before

# compare with:
y = x
(y = 0) 

# Recycling:
x[c(1,3)] = 4.5 # recycling will be used if sub-vector selected for replacement is longer than the right-hand side.

(x[10] = 8) # replacing to an index greater than the length of the vector extends it, filling in with NA's

x[11] # returns NA

# indexing matrices and arrays
mymat[1:2, -2]
mymat[mymat>1] = NA # note: no comma

mymat = matrix(1:12, 3, 4)
mymat[cbind(rep(1,3), c(2,3,4))] = NA

# If the result has length 1 in any dimension, this is dropped unless you use the argument drop=FALSE:
mydata[1:2, 1] #is a vector
class(mydata[1:2, 1])

mydata[1, 1:2] #is a data.frame
class(mydata[1, 1:2]) 

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[1] 3 4

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

a  c  f  e 
 2  6 12 10

a  c  f  e 
 2  6 12 10

a c 
2 6

b  c  e  f 
 4  6 10 12

[1] 0

[1] "a" "b" "c" "d" "e" "f"

[1] 0

[1] 8

<NA> 
  NA

[,1] [,2] [,3]
[1,] 1    7    10  
[2,] 2    8    11

[1] 179 160

[1] "integer"

weight feed     
1 179    horsebean

[1] "data.frame"

## Indexing data frames

* Data frames can be indexed like matrices, but only ```drop``` dimensions if you select from a single column, not if you select from a single row.

* If you select rows from a data frame with only one column the result will be a vector unless you use ```drop=FALSE```

* Often want to select the rows of a data frame which meet some criterion.

* use logical indexing

In [16]:
mydata[1,]
attributes(mydata[,2])

mydata[mydata$weight> 400,] #index by rows where weight is greater than 400 

weight feed     
1 179    horsebean

$levels
[1] "casein"    "horsebean" "linseed"   "meatmeal"  "soybean"   "sunflower"

$class
[1] "factor"

weight feed     
37 423    sunflower
64 404    casein

## More Examples on matrices: Lower triangular, adding matrices, eigenvalues, column sums, ...

Check out the following:

In [17]:
mymat = matrix(1:12, nrow=3, )
mymat
mymat2 = matrix(1:12, nrow=3, byrow=TRUE)
mymat2
mymat + mymat2 #componentwise addition
mymat %*% t(mymat2) #matrix multiplication

mysq = matrix(rnorm(9), nrow=3)
solve(mysq) #invert mysq

mysym = mysq 
mysym[lower.tri(mysym)] = mysym[upper.tri(mysym)] #make symmetric version of mysq
eigen(mysym) #eigen decompositions
colSums(mymat) #column sums

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

[,1] [,2] [,3] [,4]
[1,]  2    6   10   14  
[2,]  7   11   15   19  
[3,] 12   16   20   24

[,1] [,2] [,3]
[1,] 70   158  246 
[2,] 80   184  288 
[3,] 90   210  330

[,1]        [,2]       [,3]      
[1,]  0.07146669 -0.4187667  0.3390059
[2,]  1.29757118 -0.7294324 -0.1576092
[3,] -0.92321345 -0.6068482 -0.2549748

eigen() decomposition
$values
[1]  0.634857 -0.660316 -1.247812

$vectors
           [,1]       [,2]       [,3]
[1,] -0.6416955  0.7622148 0.08517897
[2,] -0.5820237 -0.5562791 0.59312901
[3,]  0.4994750  0.3310321 0.80058886


[1]  6 15 24 33

## Functions

Writing simple functions:

In [18]:
x = rnorm(100, mean=0.3, sd=1.2) # create a vector of i.i.d random numbers from a N(0.3,1.2) normal distributions


std.dev = function(x) sqrt(var(x)) # function to calculate the standard deviation of a vector

# function to calculate the two-tailed p-value of a t.test
# note that function arguments can have default values
t.test.p = function(x, mu=0)  {
    n = length(x)
    t = sqrt(n) * (mean(x) - mu) /std.dev(x)
    2 * (1 - pt(abs(t), n - 1)) # the object of the final line will be returned
}

std.dev(x)
t.test.p(x) # this will use the default value for mu
t.test.p(mu=1, x=x) 
t.test.p(x, 1)

[1] 1.165389

[1] 0.003642808

[1] 1.903917e-07

[1] 1.903917e-07

## Flow control: if, for , while, repeat


In [19]:
#function generates 3 samples of size n from U(0,1), stores the means, prints the mean of entries > 0.2 using conditional indexing
myfn = function(n=100)  
{
    tmp = rep(NA, 3)
    tmp[1] = mean(runif(n))
    tmp[2] = mean(runif(n))
    tmp[3] = mean(runif(n))
    mean(tmp[tmp > .2])
}
set.seed(1)
myfn()
myfn(1000)

[1] 0.4901114

[1] 0.4950009

## Control flow: if
Example

In [20]:
#function does the same things as the previous function but using if statements instead of conditional indexing
myfna = function(n=100)
{
    tmp = rep(NA, 3)
    x <- mean(runif(n))
    if (x > 0.2)
        tmp[1] = x
    x = mean(runif(n))
    if (x > 0.2)
        tmp[2] = x
    x = mean(runif(n))
    if (x > 0.2)
        tmp[3] = x
    mean(tmp, na.rm=TRUE)
}
set.seed(1)
myfna()
myfna(1000)

[1] 0.4901114

[1] 0.4950009

## Control Flow: For 

In [21]:
#generates n samples of size obs of U(0,1) variables and saves means in x. Returns mean and standard deviation of x 
myfn1 = function(obs=10, n=100) 
{
    x = rep(NA, n)
    for (i in 1:n)
    {
        tmp = runif(obs)
        x[i] = mean(tmp)
    }
    c(mn=mean(x), std=sd(x))
}
set.seed(1)
myfn1()
myfn1(1000)

mn        std 
0.49969167 0.09776245

mn         std 
0.499504086 0.009021776

The functions ```while``` and ```repeat``` don't require loop variables.

## The function ifelse

The function ```ifelse``` reduces the need for loops and can make code more efficient. Example:

In [22]:
x = c(0, 1, 1, 2)
y = c(44, 45, 56, 77)

z = rep(NA, 4)
for (i in 1:length(x))
{
    if (x[i] > 0)
        z[i] <- y[i] / x[i]
    else
        z[i] <- y[i] / 99
}
z

[1]  0.4444444 45.0000000 56.0000000 38.5000000

This can be replaced by:

In [23]:
(z = ifelse(x > 0, y / x, y / 99))

[1]  0.4444444 45.0000000 56.0000000 38.5000000

## Exercise: 1

*  Create a vector containing all the dates in 2007, using ```seq``` and ```as.Date```.

* There is a version of ```cut``` for dates, called ```cut.Date```. Use this to create a factor with values corresponding to the date of the first day of the week in which each of these dates falls. Start the weeks on Sundays.

* Create ```x```, a vector of length 100, with integer values in the range $1:5$, randomly ordered. (Hint: look at the function ```sample```.)

* Use ```paste``` to create a vector of labels: `("Colour 1", "Colour 2", "Colour 3", "Colour 4", "Colour 5")`

*  Use the ```factor``` command to create a factor from the vector ```x```,  with the labels created above.

* Create a data frame with 100 rows and two columns, one containing a random sample of the vector of dates created above, and the other containing the factor vector of colour names.
  
* Select the rows for which the date is after 1st June 2007.

[Solution]()

## Solution+: 1
*  Create a vector containing all the dates in 2007, using ```seq``` and ```as.Date```.

In [24]:
myDate1 = as.Date('1-Jan-2007', format="%d-%b-%Y")
myDate2 = myDate1+364
myDate2

[1] "2007-12-31"

In [25]:
dates2007 = seq(myDate1,myDate2,1)

* There is a version of ```cut``` for dates, called ```cut.Date```. Use this
  to create a factor with values corresponding to the date of the first day of
  the week in which each of these dates falls. Start the weeks on Sundays.

In [26]:
fdate = cut.Date(dates2007, "weeks",start.on.monday=FALSE)
table(fdate)

fdate
2006-12-31 2007-01-07 2007-01-14 2007-01-21 2007-01-28 2007-02-04 2007-02-11 
         6          7          7          7          7          7          7 
2007-02-18 2007-02-25 2007-03-04 2007-03-11 2007-03-18 2007-03-25 2007-04-01 
         7          7          7          7          7          7          7 
2007-04-08 2007-04-15 2007-04-22 2007-04-29 2007-05-06 2007-05-13 2007-05-20 
         7          7          7          7          7          7          7 
2007-05-27 2007-06-03 2007-06-10 2007-06-17 2007-06-24 2007-07-01 2007-07-08 
         7          7          7          7          7          7          7 
2007-07-15 2007-07-22 2007-07-29 2007-08-05 2007-08-12 2007-08-19 2007-08-26 
         7          7          7          7          7          7          7 
2007-09-02 2007-09-09 2007-09-16 2007-09-23 2007-09-30 2007-10-07 2007-10-14 
         7          7          7          7          7          7          7 
2007-10-21 2007-10-28 2007-11-04 2007-11-11 2007-11-18 200

* Create ```x```, a vector of length 100, with integer values in the range
  $1:5$, randomly ordered. (Hint: look at the function ```sample```.)

In [27]:
sample(1:5,100,replace=TRUE)

[1] 5 3 4 3 2 3 2 2 5 2 5 1 3 3 2 2 1 3 5 1 5 3 4 5 1 1 1 4 4 4 1 5 4 3 1 2 5
 [38] 4 5 3 1 4 5 2 5 1 5 5 2 5 2 4 4 1 3 4 1 2 1 5 3 5 2 4 2 2 1 1 4 1 4 5 1 1
 [75] 4 5 3 4 3 3 5 1 1 3 2 1 2 1 3 2 1 4 3 1 2 5 5 5 5 3

* Use ```paste``` to create a vector of labels:
    ("Colour 1", "Colour 2", "Colour 3", "Colour 4", "Colour 5")

In [28]:
x = paste("Colour",1:5)
x

[1] "Colour 1" "Colour 2" "Colour 3" "Colour 4" "Colour 5"

*  Use the ```factor``` command to create a factor from the vector ```x```,
  with the labels created above.

In [29]:
xf = factor(x)
table(xf)

xf
Colour 1 Colour 2 Colour 3 Colour 4 Colour 5 
       1        1        1        1        1 

* Create a data frame with 100 rows and two columns, one containing a random
  sample of the vector of dates created above, and the other containing the
  factor vector of colour names.

In [30]:
(datf = data.frame(d=sample(dates2007,100,replace=TRUE),c=xf)  )

d          c       
1   2007-11-10 Colour 1
2   2007-03-03 Colour 2
3   2007-10-24 Colour 3
4   2007-11-10 Colour 4
5   2007-08-25 Colour 5
6   2007-04-27 Colour 1
7   2007-03-03 Colour 2
8   2007-04-06 Colour 3
9   2007-05-13 Colour 4
10  2007-01-14 Colour 5
11  2007-09-25 Colour 1
12  2007-05-20 Colour 2
13  2007-07-19 Colour 3
14  2007-11-08 Colour 4
15  2007-11-03 Colour 5
16  2007-06-04 Colour 1
17  2007-07-04 Colour 2
18  2007-07-03 Colour 3
19  2007-08-04 Colour 4
20  2007-08-20 Colour 5
21  2007-11-20 Colour 1
22  2007-08-16 Colour 2
23  2007-01-25 Colour 3
24  2007-04-07 Colour 4
25  2007-12-19 Colour 5
26  2007-12-25 Colour 1
27  2007-11-29 Colour 2
28  2007-06-19 Colour 3
29  2007-11-21 Colour 4
30  2007-01-25 Colour 5
... ...        ...     
71  2007-12-02 Colour 1
72  2007-03-28 Colour 2
73  2007-09-15 Colour 3
74  2007-04-06 Colour 4
75  2007-09-10 Colour 5
76  2007-02-23 Colour 1
77  2007-11-14 Colour 2
78  2007-12-31 Colour 3
79  2007-06-14 Colour 4
80  2007-05-06 Colour 5
81  2007-04-15 Colour 1
82  2007-02-14 Colour 2
83  2007-11-26 Colour 3
84  2007-08-05 Colour 4
85  2007-08-25 Colour 5
86  2007-07-05 Colour 1
87  2007-07-31 Colour 2
88  2007-09-21 Colour 3
89  2007-09-10 Colour 4
90  2007-03-05 Colour 5
91  2007-12-11 Colour 1
92  2007-12-14 Colour 2
93  2007-11-02 Colour 3
94  2007-10-25 Colour 4
95  2007-03-05 Colour 5
96  2007-02-16 Colour 1
97  2007-01-13 Colour 2
98  2007-07-24 Colour 3
99  2007-02-27 Colour 4
100 2007-05-14 Colour 5

  
* Select the rows for which the date is after 1st June 2007.

In [31]:
datf[datf$d-as.Date('1-June-2007', format="%d-%b-%Y")>0,]

d          c       
1   2007-11-10 Colour 1
3   2007-10-24 Colour 3
4   2007-11-10 Colour 4
5   2007-08-25 Colour 5
11  2007-09-25 Colour 1
13  2007-07-19 Colour 3
14  2007-11-08 Colour 4
15  2007-11-03 Colour 5
16  2007-06-04 Colour 1
17  2007-07-04 Colour 2
18  2007-07-03 Colour 3
19  2007-08-04 Colour 4
20  2007-08-20 Colour 5
21  2007-11-20 Colour 1
22  2007-08-16 Colour 2
25  2007-12-19 Colour 5
26  2007-12-25 Colour 1
27  2007-11-29 Colour 2
28  2007-06-19 Colour 3
29  2007-11-21 Colour 4
31  2007-11-07 Colour 1
33  2007-12-14 Colour 3
34  2007-06-23 Colour 4
35  2007-08-16 Colour 5
36  2007-11-24 Colour 1
38  2007-06-29 Colour 3
41  2007-07-30 Colour 1
47  2007-06-29 Colour 2
48  2007-07-23 Colour 3
49  2007-10-12 Colour 4
... ...        ...     
51  2007-10-29 Colour 1
52  2007-07-05 Colour 2
53  2007-09-14 Colour 3
56  2007-10-13 Colour 1
57  2007-09-18 Colour 2
58  2007-11-12 Colour 3
59  2007-11-26 Colour 4
63  2007-07-05 Colour 3
64  2007-10-09 Colour 4
65  2007-11-20 Colour 5
66  2007-08-01 Colour 1
67  2007-12-16 Colour 2
71  2007-12-02 Colour 1
73  2007-09-15 Colour 3
75  2007-09-10 Colour 5
77  2007-11-14 Colour 2
78  2007-12-31 Colour 3
79  2007-06-14 Colour 4
83  2007-11-26 Colour 3
84  2007-08-05 Colour 4
85  2007-08-25 Colour 5
86  2007-07-05 Colour 1
87  2007-07-31 Colour 2
88  2007-09-21 Colour 3
89  2007-09-10 Colour 4
91  2007-12-11 Colour 1
92  2007-12-14 Colour 2
93  2007-11-02 Colour 3
94  2007-10-25 Colour 4
98  2007-07-24 Colour 3

:Solution+

## Exercise: 2

* Generate a matrix with 10 rows and 5 columns, with random entries between 0 and 10. (Hint: look at ```runif```)

*  Write a function using ```for``` to calculate the column means of the matrix.

*  Extract the even rows from the matrix.

[Solution]()

## Solution+: 2

* Generate a matrix with 10 rows and 5 columns, with random entries
  between 0 and 10. (Hint: look at ```runif```)

In [32]:
matti = matrix(runif(50,0,10),nrow=10)
matti

[,1]     [,2]      [,3]      [,4]       [,5]    
 [1,] 9.804293 4.9836626 0.7089561 0.64035735 8.655358
 [2,] 1.535470 6.3303802 9.0285600 9.58436689 2.117108
 [3,] 7.054454 0.2246136 6.6611312 6.70334340 7.309426
 [4,] 4.752587 6.0213062 7.7713002 0.07117314 3.526904
 [5,] 3.143838 5.7364747 0.4074274 4.43395158 7.922231
 [6,] 3.176729 1.3561584 2.1107383 2.28420872 6.819195
 [7,] 5.302103 9.8258713 9.2962555 4.64784942 3.751291
 [8,] 5.985252 2.3348505 7.1433309 0.54225692 6.742854
 [9,] 7.494877 1.6589038 0.6764284 9.18624923 9.676256
[10,] 1.905350 7.5088342 9.7672090 9.56431339 5.387983

*  Write a function using ```for``` to calculate the column means of
  the matrix.

In [33]:
for (i in 1:5) mean(matti[,i])
apply(matti,2,mean)

[1] 5.015495 4.598106 5.357134 4.765807 6.190861

*  Extract the even rows from the matrix.

In [34]:
matti[seq(2,10,2),]

[,1]     [,2]     [,3]     [,4]       [,5]    
[1,] 1.535470 6.330380 9.028560 9.58436689 2.117108
[2,] 4.752587 6.021306 7.771300 0.07117314 3.526904
[3,] 3.176729 1.356158 2.110738 2.28420872 6.819195
[4,] 5.985252 2.334851 7.143331 0.54225692 6.742854
[5,] 1.905350 7.508834 9.767209 9.56431339 5.387983

: solution+